apiVersion: v1
kind: ServiceAccount
metadata:
  name: server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-read
rules:
  - apiGroups: [""] #Determina quais os recursos ele pode acessar.
    resources: ["pods","services"] #Tipos de serviços que ele podem acessar.
    verbs: ["get","watch","list"] #São os comandos que podem ser executados nos recursos acima.
  - apiGroups: ["apps"] #Determina quais os recursos o deployments pode usar.
    resources: ["deployments"] #Tipos de serviços que ele podem acessar.
    verbs: ["get","watch","list"] #São os comandos que podem ser executados nos recursos acima.

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-read-bind
subjects:
  - kind: ServiceAccount
    name: server
    #namespace: prod
  roleRef:
    kind: Role
    name: server-read
    apiGroups: rbac.authorization.k8s.io
